services:
  web:
    container_name: django_app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
       - "8000:8000"
    depends_on:
        - db
    env_file:
      - .env
    volumes:
       - ./e_commerce:/app

  db:
    container_name: postgres
    image: postgres:13
    environment:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_HOST: "${POSTGRES_HOST}"
        POSTGRES_PORT: "${POSTGRES_PORT}"
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env

  test:
    container_name: pytest
    build: .
    command: pytest
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./e_commerce:/app/

